
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>File Manager</title>
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">

    <title>File Manager</title>
</head>


  <body>

  <div class="container" id="content-container-admin">

      <div class="starter-template">

          <h2><?=\Library\Session::getFlash()?></h2>

          <br>
          <?=$content ?>

          <!--<h1>Bootstrap starter template</h1>-->
          <!--<p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>-->
      </div>

  </div><!-- /.container -->


  </body>
</html>


